### PR TITLE
Add support for FA Persian language locale

### PR DESCRIPTION
**Pull request by SMSadegh19**
Hi!
I've added locale for Persian language.

PR sent with Love.❤️

### CODE REVIEW

**Comment by nleeper** [comment]
Looks like a failing test. Happy to merge once tests are passing!

**Comment by nleeper** [comment]
> Looks like a failing test. Happy to merge once tests are passing!

Nevermind, looks like a flaky ISO test I need to fix 😄 I'll get this merged and a new version cut. Thanks!

**Comment by SMSadegh19** [comment]
Thanks a lot! :)
Thank you for your efforts and creating this library.

**Comment by SMSadegh19** [comment]
Hi Nick,

Thank you again for Goment. 🔥 ❤️

I’m really happy to see that I was one of the contributors to this repository! :)

To support my open-source activities, you can make me even happier by visiting this link: 😄
https://buymeacoffee.com/centrifugalforce

**Pull request merged**
